DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL,
    full_name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE IF NOT EXISTS datarecords (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    A INTEGER DEFAULT -1,
    GD INTEGER DEFAULT -1,
    EN INTEGER DEFAULT -1,
    MK INTEGER DEFAULT -1,
    E INTEGER DEFAULT -1,
    EMP INTEGER DEFAULT 0,
    DID TEXT DEFAULT "ADLYTIC",
    T TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    I TEXT DEFAULT " ",
    CID TEXT DEFAULT " ",
    RID TEXT DEFAULT " "

);

CREATE TABLE IF NOT EXISTS allSettings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    k TEXT DEFAULT -1,
    v TEXT DEFAULT -1
);



CREATE TABLE IF NOT EXISTS settings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    k TEXT DEFAULT -1,
    v TEXT DEFAULT -1
);



CREATE TABLE IF NOT EXISTS idBank (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    _id TEXT DEFAULT -1
);