export const actionTypes = {
    SETTINGS_GET : "SETTINGS_GET",
    SETTINGS_SET : "SETTINGS_SET",
    DATA_TOTAL : "DATA_TOTAL",
    DATA_GRAPH : "DATA_GRAPH", 
    DATA_THUMBS : "DATA_THUMBS", 
    DATA_JOURNEY: "DATA_JOURNEY",
    DATA_QUEUE: "DATA_QUEUE",
    SETTINGS_LOADER : "SETTINGS_LOADER",
    SETTINGS_RESPONSE : "SETTINGS_RESPONSE",
    FILTER : "FILTER",
    SET_ALL_SETTINGS : "SET_ALL_SETTINGS",
    DATA_TABLE : "DATA_TABLE",
    SET_DETAILS : "SET_DETAILS",
  
}